resultadoAckley1 <- read.table("master-slave-Ackley-1.csv",header=TRUE)
resultadoAckley2 <- read.table("master-slave-Ackley-2.csv",header=TRUE)
resultadoAckley4 <- read.table("master-slave-Ackley-4.csv",header=TRUE)
resultadoQuadric1 <- read.table("master-slave-Quadric-1.csv",header=TRUE)
resultadoQuadric2 <- read.table("master-slave-Quadric-2.csv",header=TRUE)
resultadoQuadric4 <- read.table("master-slave-Quadric-4.csv",header=TRUE)
resultadoRastrigin1 <- read.table("master-slave-Rastrigin-1.csv",header=TRUE)
resultadoRastrigin2 <- read.table("master-slave-Rastrigin-2.csv",header=TRUE)
resultadoRastrigin4 <- read.table("master-slave-Rastrigin-4.csv",header=TRUE)
resultadoSpherical1 <- read.table("master-slave-Spherical-1.csv",header=TRUE)
resultadoSpherical2 <- read.table("master-slave-Spherical-2.csv",header=TRUE)
resultadoSpherical4 <- read.table("master-slave-Spherical-4.csv",header=TRUE)
par(mfrow=c(2,2))
plot(seq(1,length(resultadoAckley1$value)),resultadoAckley1$value,type='l',col='red',log='x',xlab="Iterations",ylab="Value",main="Ackley Benchmark")
lines(resultadoAckley2$value,type='l',col='blue')
lines(resultadoAckley4$value,type='l',col='green')
legend("topright", legend=c("1 Worker", "2 Workers","3 Workers"),
       col=c("red", "blue","green"), lty=1, cex=0.8)
plot(seq(1,length(resultadoQuadric1$value)),resultadoQuadric1$value,type='l',col='red',log='x',xlab="Iterations",ylab="Value",main="Quadric Benchmark")
lines(resultadoQuadric2$value,type='l',col='blue')
lines(resultadoQuadric4$value,type='l',col='green')
legend("topright", legend=c("1 Worker", "2 Workers","3 Workers"),
       col=c("red", "blue","green"), lty=1, cex=0.8)
plot(seq(1,length(resultadoRastrigin1$value)),resultadoRastrigin1$value,type='l',col='red',log='x',xlab="Iterations",ylab="Value",main="Rastrigin Benchmark")
lines(resultadoRastrigin2$value,type='l',col='blue')
lines(resultadoRastrigin4$value,type='l',col='green')
legend("topright", legend=c("1 Worker", "2 Workers","3 Workers"),
       col=c("red", "blue","green"), lty=1, cex=0.8)
plot(seq(1,length(resultadoSpherical1$value)),resultadoSpherical1$value,type='l',col='red',log='x',xlab="Iterations",ylab="Value",main="Spherical Benchmark")
lines(resultadoSpherical2$value,type='l',col='blue')
lines(resultadoSpherical4$value,type='l',col='green')
legend("topright", legend=c("1 Worker", "2 Workers","3 Workers"),
       col=c("red", "blue","green"), lty=1, cex=0.8)