library(beanplot)
resultadoAckleySec <- read.table("secStatisticsAckley.csv",header=TRUE)
resultadoAckley1 <- read.table("master-slave-stat-Ackley-1.csv",header=TRUE)
resultadoAckley2 <- read.table("master-slave-stat-Ackley-2.csv",header=TRUE)
resultadoAckley4 <- read.table("master-slave-stat-Ackley-4.csv",header=TRUE)
resultadoQuadricSec <- read.table("secStatisticsQuadric.csv",header=TRUE)
resultadoQuadric1 <- read.table("master-slave-stat-Quadric-1.csv",header=TRUE)
resultadoQuadric2 <- read.table("master-slave-stat-Quadric-2.csv",header=TRUE)
resultadoQuadric4 <- read.table("master-slave-stat-Quadric-4.csv",header=TRUE)
resultadoRastriginSec <- read.table("secStatisticsRastrigin.csv",header=TRUE)
resultadoRastrigin1 <- read.table("master-slave-stat-Rastrigin-1.csv",header=TRUE)
resultadoRastrigin2 <- read.table("master-slave-stat-Rastrigin-2.csv",header=TRUE)
resultadoRastrigin4 <- read.table("master-slave-stat-Rastrigin-4.csv",header=TRUE)
resultadoSphericalSec <- read.table("secStatisticsSpherical.csv",header=TRUE)
resultadoSpherical1 <- read.table("master-slave-stat-Spherical-1.csv",header=TRUE)
resultadoSpherical2 <- read.table("master-slave-stat-Spherical-2.csv",header=TRUE)
resultadoSpherical4 <- read.table("master-slave-stat-Spherical-4.csv",header=TRUE)
par(mfrow=c(2,2))
beanplot(resultadoAckleySec$value,resultadoAckley1$value,resultadoAckley2$value,resultadoAckley4$value,main="Ackley Benchmark",xlab="Workers",ylab="Value",col = c("#CAB2D6", "#33A02C", "#B2DF8A"), border = "#CAB2D6",what=c(0,1,1,0),show.names=FALSE)
axis(1,at=c(1,2,3,4),labels=c("Sec","1","2","4"))
beanplot(resultadoQuadricSec$value,resultadoQuadric1$value,resultadoQuadric2$value,resultadoQuadric4$value,main="Quadric Benchmark",xlab="Workers",ylab="Value",col = c("#CAB2D6", "#33A02C", "#B2DF8A"), border = "#CAB2D6",what=c(0,1,1,0),show.names=FALSE)
axis(1,at=c(1,2,3,4),labels=c("Sec","1","2","4"))
beanplot(resultadoRastriginSec$value,resultadoRastrigin1$value,resultadoRastrigin2$value,resultadoRastrigin4$value,main="Rastrigin Benchmark",xlab="Workers",ylab="Value",col = c("#CAB2D6", "#33A02C", "#B2DF8A"), border = "#CAB2D6",what=c(0,1,1,0),show.names=FALSE)
axis(1,at=c(1,2,3,4),labels=c("Sec","1","2","4"))
beanplot(resultadoSphericalSec$value,resultadoSpherical1$value,resultadoSpherical2$value,resultadoSpherical4$value,main="Spherical Benchmark",xlab="Workers",ylab="Value",col = c("#CAB2D6", "#33A02C", "#B2DF8A"), border = "#CAB2D6",what=c(0,1,1,0),show.names=FALSE)
axis(1,at=c(1,2,3,4),labels=c("Sec","1","2","4"))